package main

type Game struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

var snesGames = []Game{
	Game{1, "Teenage Mutant Ninja Turtles IV: Turtles in Time"},
	Game{2, "Star Fox"},
	Game{3, "Donkey Kong Country"},
	Game{4, "Super Castlevania IV"},
	Game{5, "Super Mario RPG"},
	Game{6, "Super Mario Kart"},
	Game{7, "Street Fighter II"},
	Game{8, "Final Fantasy IV"},
	Game{9, "Super Mario World"},
	Game{10, "Chrono Trigger"},
	Game{11, "Earthbound"},
	Game{12, "The Legend of Zelda: A Link to the Past"},
	Game{13, "Shadowrun"},
	Game{14, "Super Metroid"},
	Game{15, "Final Fantasy VI"},
	Game{16, "Super Ghouls ‘n Ghosts"},
	Game{17, "F-Zero"},
	Game{18, "Mortal Kombat II"},
	Game{19, "Super Punch-Out!!"},
	Game{20, "Harvest Moon"},
	Game{21, "Final Fight"},
	Game{22, "Super Star Wars"},
	Game{23, "Earthworm Jim"},
	Game{24, "Kirby’s Dream Course"},
	Game{25, "SimCity"},
	Game{26, "Super Star Wars: Return of the Jedi"},
	Game{27, "Donkey Kong Country 3: Dixie Kong’s Double Trouble"},
	Game{28, "Illusion of Gaia"},
	Game{29, "Zombies Ate My Neighbors"},
	Game{30, "Earthworm Jim 2"},
	Game{31, "Mega Man X"},
	Game{32, "Mario Paint"},
	Game{33, "Donkey Kong Country 2: Diddy’s Kong Quest"},
	Game{34, "Super Mario World 2: Yoshi’s Island"},
	Game{35, "NBA Jam"},
	Game{36, "Contra 3: The Alien Wars"},
	Game{37, "Secret of Mana"},
	Game{38, "Actraiser"},
	Game{39, "Super Bomberman"},
	Game{40, "Kirby Super Star"},
	Game{41, "Mortal Kombat"},
	Game{42, "Mega Man X2"},
	Game{43, "Tetris Attack"},
	Game{44, "Tecmo Super Bowl"},
	Game{45, "Disney’s Aladdin"},
	Game{46, "Pilotwings"},
	Game{47, "Doom"},
	Game{48, "Secrets of Evermore"},
	Game{49, "The Lion King"},
	Game{50, "Demon’s Crest"},
	Game{51, "Mega Man X3"},
	Game{52, "Super Star Wars: The Empire Strikes Back"},
	Game{53, "Castlevania: Dracula X"},
	Game{54, "Clay Fighter"},
	Game{55, "Batman Returns"},
	Game{56, "Ogre Battle: March of the Black Queen"},
	Game{57, "Final Fight 2"},
	Game{58, "Final Fight 3"},
	Game{59, "Knights of the Round"},
	Game{60, "Star Ocean"},
	Game{61, "Star Fox 2"},
	Game{62, "Breath of Fire"},
	Game{63, "Breath of Fire II"},
	Game{64, "Ultimate Mortal Kombat 3"},
	Game{65, "Hagane: The Final Conflict"},
	Game{66, "Populous"},
	Game{67, "Joe & Mac"},
	Game{68, "NBA Hangtime"},
	Game{69, "Primal Rage"},
	Game{70, "Shin Megami Tensei"},
	Game{71, "Super Mario All-Stars"},
	Game{72, "Killer Instinct"},
	Game{73, "NBA Jam Tournament Edition"},
	Game{74, "Terranigma"},
	Game{75, "The Lost Vikings"},
	Game{76, "The Legend of the Mystical Ninja"},
	Game{77, "Top Gear"},
	Game{78, "Super R-Type"},
	Game{79, "Rock n’ Roll Racing"},
	Game{80, "Tiny Toons Adventures: Buster Busts Loose!"},
	Game{81, "The Magical Quest Starring Mickey Mouse"},
	Game{82, "Tales of Phantasia"},
	Game{83, "Final Fantasy V"},
	Game{84, "Jurassic Park"},
	Game{85, "Top Gear 2"},
	Game{86, "Ken Griffey Jr. Presents Major League Baseball"},
	Game{87, "Lufia and the Fortress of Doom"},
	Game{88, "Lufia II: Rise of the Sinistrals"},
	Game{89, "NHL 94"},
	Game{90, "Super Tennis"},
	Game{91, "NHL 96"},
	Game{92, "Blackthorne"},
	Game{93, "Indiana Jones’ Greatest Adventures"},
	Game{94, "Yoshi’s Cookie"},
	Game{95, "Flashback"},
	Game{96, "Battletoads in Battlemaniacs"},
	Game{97, "Krusty’s Fun House"},
	Game{98, "Fatal Fury Special"},
	Game{99, "The Simpsons: Bart’s Nightmare"},
	Game{100, "Toy Story"},
}
